USE [Master]
CREATE DATABASE [[DATABASE_NAME]] ON  PRIMARY
( NAME = N'[DATABASE_NAME]', FILENAME = N'[DATABASE_FILE_DIRECTORY]\[DATABASE_NAME]_Data.mdf' , SIZE = 10048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
LOG ON
( NAME = N'[DATABASE_NAME]_Log', FILENAME = N'[DATABASE_FILE_DIRECTORY]\[DATABASE_NAME]_Log.ldf' , SIZE = 10024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)

ALTER DATABASE [[DATABASE_NAME]] SET ANSI_NULL_DEFAULT ON
ALTER DATABASE [[DATABASE_NAME]] SET ANSI_NULLS OFF
ALTER DATABASE [[DATABASE_NAME]] SET ANSI_PADDING OFF
ALTER DATABASE [[DATABASE_NAME]] SET ANSI_WARNINGS OFF
ALTER DATABASE [[DATABASE_NAME]] SET ARITHABORT OFF
ALTER DATABASE [[DATABASE_NAME]] SET AUTO_CLOSE OFF
ALTER DATABASE [[DATABASE_NAME]] SET AUTO_CREATE_STATISTICS ON
ALTER DATABASE [[DATABASE_NAME]] SET AUTO_SHRINK OFF
ALTER DATABASE [[DATABASE_NAME]] SET AUTO_UPDATE_STATISTICS ON
ALTER DATABASE [[DATABASE_NAME]] SET CURSOR_CLOSE_ON_COMMIT OFF
ALTER DATABASE [[DATABASE_NAME]] SET CURSOR_DEFAULT  GLOBAL
ALTER DATABASE [[DATABASE_NAME]] SET CONCAT_NULL_YIELDS_NULL OFF
ALTER DATABASE [[DATABASE_NAME]] SET NUMERIC_ROUNDABORT OFF
ALTER DATABASE [[DATABASE_NAME]] SET QUOTED_IDENTIFIER OFF
ALTER DATABASE [[DATABASE_NAME]] SET RECURSIVE_TRIGGERS OFF
ALTER DATABASE [[DATABASE_NAME]] SET  DISABLE_BROKER
ALTER DATABASE [[DATABASE_NAME]] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [[DATABASE_NAME]] SET DATE_CORRELATION_OPTIMIZATION OFF
ALTER DATABASE [[DATABASE_NAME]] SET TRUSTWORTHY OFF
ALTER DATABASE [[DATABASE_NAME]] SET ALLOW_SNAPSHOT_ISOLATION OFF
ALTER DATABASE [[DATABASE_NAME]] SET PARAMETERIZATION SIMPLE
ALTER DATABASE [[DATABASE_NAME]] SET  READ_WRITE
ALTER DATABASE [[DATABASE_NAME]] SET RECOVERY FULL
ALTER DATABASE [[DATABASE_NAME]] SET  MULTI_USER
ALTER DATABASE [[DATABASE_NAME]] SET PAGE_VERIFY TORN_PAGE_DETECTION
ALTER DATABASE [[DATABASE_NAME]] SET DB_CHAINING OFF